### ISSUE TITLE
pushwoosh for marmalade should not contain its own version of google-play-services etc

### ISSUE THREAD

**Issue by john-forrest** [Pushwoosh/pushwoosh-marmalade#2]
Many marmalade extensions use google-play-services.jar and android-support-v4.jar. In the past, when they each contained their own version, this caused users multiple issues when using multiple extensions because i) they would have to go and hack the various mkf files to delete the entry in all but one and ii) different extensions might contain files with different versions and you needed to work out which was the latest.

To get around this, the Marmalade SDK includes projects google-play-services-android and android-support-v4, which pull in the bundled copy of the libraries. Due to the way the marmalade subproject scheme works, they can be referenced from multiple extensions but the associated .jar is only included once.

Unfortunately this extensions has been updated following the old pattern, which will (and actually does) cause users problems if they use pushwoosh along with one of the other extensions using google-play-services. The fix should be simply to delete the lines:

    android-external-jars="android-support-v4.jar"
    android-external-jars="google-play-services.jar"

in the mkf file and to add:

    subproject google-play-services-android

a little further up outside the "deployments" section. See s3eGooglePlayServices.mkf (in any recent Marmalade SDK) as an example.

**Comment by shaders** [comment]
Thanks! Going to update this soon.

**Comment by NuriaPlanell** [comment]
For the record, you may also need to rebuild the pushwoosh.jar against the Marmalade included version of Google Play Services as just changing the above mentioned lines on the .mkf results in a crash:

_java.lang.IncompatibleClassChangeError: The method 'void com.google.android.gms.common.api.GoogleApiClient.connect()' was expected to be of type virtual but instead was found to be of type interface (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)_

**Comment by DimanAM** [comment]
Marmalade is shipped with google-play-services version 6.5 wich is not compatible with Pushwoosh.jar. Pushwoosh SDK requires at least 8.0 version of google-play-services. 
The only way to resolve google-play-services and android-support-v4 conflicts right now is to remove duplicate references to these libraries manually.

**Comment by john-forrest** [comment]
That would not really be working because, as soon as a user wishes to use another module that required GPS, it would break.

Having said that, the latest patch release (8.3p3) of the Marmalade SDK ships with 8.48 of google-play-services.

**Comment by DimanAM** [comment]
> Having said that, the latest patch release (8.3p3) of the Marmalade SDK ships with 8.48 of google-play-services.

Thank for the information. I haven't noticed these patches.
Pushwoosh extension now references subproject **google-play-services-android** and requires at least Marmalade SDK 8.3p2.
