### ISSUE TITLE
s3ePushWoosh badges

### ISSUE THREAD

**Issue by ghost** [Pushwoosh/pushwoosh-marmalade#3]
Hi folks,

For local iOS pushes we used a native Marmalade extension s3eIOSNotifications, but recently migrated to s3ePushWoosh. Each push in the s3eIOSNotifications creates from a structure that have the "m_BadgeNo" parameter, so I can easily increment this value while creating pushes on app exit or lost focus.

```
typedef struct s3eIOSNotificationsEventInfo
{
    const char*     m_EventName;
    const char*     m_EventMessage;
    uint64          m_FireDateS;
    uint16          m_BadgeNo;
    const char*     m_EventData;
    const char*     m_Category;
    const char*     m_ActionId;
} s3eIOSNotificationsEventInfo;
```

Could you explain how to do the same thing in s3ePushWoosh?

Right now the function s3ePushWooshNotificationSetBadgeNumber(int badgeValue) seems to be useless.

**Comment by wfhm** [comment]
Hi,

Thanks for the info! We have put adding a similar functionality to our Marmalade extension, and as soon as it is done we will update this thread.
