### ISSUE TITLE
ios8 libs version

### ISSUE THREAD

**Issue by Jakub-Doucek** [Pushwoosh/pushwoosh-marmalade#4]
Hi,

I need to rebuild pushwoosh extension to support ios 8. Now I'm getting Undefined symbols because current version is build with ios 6.0 as Deployment Target. Best solution for me is to get the full source code to be able to rebuild extension in way I need. Is that possible?

`Undefined symbols for architecture arm64:
  "std::string::operator=(char const*)", referenced from:
      -[UIApplication(InternalPushRuntime) onDidRegisterForRemoteNotificationsWithDeviceToken:] in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
      -[UIApplication(InternalPushRuntime) onDidFailToRegisterForRemoteNotificationsWithError:] in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
      -[UIApplication(InternalPushRuntime) onPushAccepted:withNotification:onStart:] in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()", referenced from:
      ___cxx_global_var_init in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
      ___cxx_global_var_init1 in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
      ___cxx_global_var_init2 in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()", referenced from:
      ___cxx_global_var_init in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
      ___cxx_global_var_init1 in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
      ___cxx_global_var_init2 in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
  "std::string::empty() const", referenced from:
      s3ePushWooshNotificationRegister_platform() in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
  "std::string::c_str() const", referenced from:
      -[UIApplication(InternalPushRuntime) onDidRegisterForRemoteNotificationsWithDeviceToken:] in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
      -[UIApplication(InternalPushRuntime) onDidFailToRegisterForRemoteNotificationsWithError:] in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
      -[UIApplication(InternalPushRuntime) onPushAccepted:withNotification:onStart:] in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
      s3ePushWooshNotificationRegister_platform() in libs3ePushWoosh_d.a(s3ePushWoosh_platform.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by wfhm** [comment]
Hi,

We have dropped support of pushwoosh-marmalade nearly 2 years ago, so there will be no updates to this lib in future. Source code will be opened to public access in the nearest future.

**Comment by wfhm** [comment]
@Jakub-Doucek Sources for the plugin are committed now.
